### ISSUE TITLE
bug in Database_connections_example.R

### ISSUE THREAD

**Issue by demar01** [nhs-r-community/Webinars#11]
Great webinar! 
There is an error that is carry out throughout  the Database_connections_example.R
 
group_by(type) %>%
    count() 

should be 

 group_by(type) %>%
   summarise(Count = n())

**Comment by chrismainey** [comment]
Hi @demar01 , thanks contacting.  As far as I know, both are valid syntax, which is why I've presented three ways (along with tally()) for doing it.  I don't think I'm mistaken there, as they run on my machine, unless I've misunderstood.
