### ISSUE TITLE
Accessibility - change "here" to more descriptive link

### ISSUE THREAD

**Issue by Lextuga007** [nhs-r-community/Webinars#13]
Following the thread https://twitter.com/Em1lySm/status/1516741011422199810 it's advisable to not just use "here" as a link for accessibility.

https://github.com/nhs-r-community/Webinars/blob/866873e29dae77670df842bb4272f14e353cc49b/code_of_conduct.md

**Comment by RoyTheJet** [comment]
Hello, not sure how to contribute to you all, but would love to help out. Let me know and I'll get right on it, thanks

**Comment by ChrisBeeley** [comment]
Does this help https://opensource.com/article/19/7/create-pull-request-github?

Are you on NHS-R Slack? Feel free to Slack me there with any questions, or DM on twitter @chrisbeeley

**Comment by RoyTheJet** [comment]
No, I am not on NHS-R Slack. Do I need to be? Thanks for the info as well.

**Comment by ChrisBeeley** [comment]
No, just checking if you had any questions.

I'll make a response to the PR over on the PR itself
